# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      version_update_type:
        description: 'npm package version update type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - major
          - minor
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      #- run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: git config --global user.email "git_action@xyfy.com"
      - run: git config --global user.name "Manual publish"
      - run: npm version ${{ inputs.version_update_type }} 
      - run: ${{ secrets.NPM_TOKEN }}
      - run: npm login
      - run: npm publish
      - run: git push
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
